Repository akramaznakour/research-activities-client, pull requests merged in 2020-08, with the labels that each got.

#43 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#44 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#45 Create LICENSE
  LICENSE
Labels: documentation

#47 organizational chart added
  package-lock.json
  package.json
  src/assets/css/orgChart.css
  src/views/ManagingEntities/LabReport.js
  src/views/ManagingEntities/LabTree.js
  src/views/ManagingEntities/Teams.js
  src/views/ManagingEntities/mychart.js
Labels: enhancement

#49 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#50 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#51 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#52 Update README.md fix #35
  README.md
Labels: documentation

#55 Feature show source journal or conference of publications
  src/views/Author/Author.js
  src/views/Author/components/Publication.js
  src/views/Author/components/Publications.js
Labels: enhancement

#57 Feature store new publication notification
  src/api/ApiServices.js
  src/api/services.js
  src/views/Author/Author.js
  src/views/Author/components/AuthorHeader.js
  src/views/Author/components/Publication.js
  src/views/layout/Notifications.js
Labels: enhancement

#59 Develop feature: store new publication notification
  src/api/ApiServices.js
  src/api/services.js
  src/views/Author/Author.js
  src/views/Author/components/AuthorHeader.js
  src/views/Author/components/Publication.js
  src/views/layout/Notifications.js
Labels: enhancement

#63 Feature store new publication notification
  src/context/AppContext.js
  src/views/Author/Author.js
  src/views/layout/Notifications.js
Labels: enhancement

#64 Chore scholar id to author
  src/api/services.js
  src/assets/css/orgChart.css
  src/routes/routes.js
  src/views/Author/Author.js
  src/views/Author/components/Publication.js
  src/views/ManagingEntities/LabTree.js
  src/views/ManagingEntities/mychart.js
  src/views/layout/Notifications.js
Labels: enhancement

#65 Feature add no result found to searchs and filters
  src/views/ManagingAccounts/FollowedResearchers.js
  src/views/Statistics/Statistics.js
Labels: enhancement

#67 Develop: notifications storing and scraper update
  src/api/services.js
  src/context/AppContext.js
  src/routes/routes.js
  src/views/Author/Author.js
  src/views/Author/components/Publication.js
  src/views/ManagingAccounts/FollowedResearchers.js
  src/views/Statistics/Statistics.js
  src/views/layout/Notifications.js
Labels: bug, enhancement

#69 Fix author card size
  src/views/Author/components/AuthorCard.js
Labels: bug

#72 Hotfix author card fixed size
  src/views/Author/components/AuthorCard.js
Labels: bug

#73 Hotfix new publication alert
  src/views/Author/Author.js
  src/views/layout/Notifications.js
Labels: bug

#74 Limit sending alerts to debug mode
  src/context/AppContext.js
Labels: enhancement

#76 Feature scrape author data from scopus
  src/routes/routes.js
  src/views/Author/Author.js
  src/views/Author/AuthorReport.js
  src/views/Author/components/AuthorCard.js
  src/views/Author/components/AuthorHeader.js
  src/views/Author/components/Publication.js
  src/views/Author/components/Publications.js
Labels: enhancement

#75 Oussama
  src/routes/routes.js
  src/views/Statistics/TeamsStatistics.js
  src/views/Statistics/labStatistics.js
  src/views/components/LabFilter.js
  src/views/components/TeamFilter.js
Labels: enhancement

#79 Bugfix getting publication journal metrics
  src/views/Author/components/Publication.js
Labels: bug

#80 Bugfix author card sizing
  src/views/Author/components/AuthorCard.js
Labels: bug

#81 Enable following authors from scopus
  src/views/Author/Author.js
Labels: enhancement

#82 Add first letters avatar to scopus followed authors
  src/views/Statistics/components/StatisticsTable.js
Labels: enhancement

#85 Research director designation view changed
  src/views/ManagingAccounts/ResearchDirector.js
Labels: enhancement

#87 Feature extend notifications to followed scopus authors
  src/api/services.js
  src/views/layout/Notifications.js
Labels: enhancement

#92 Update string size from 40 to 30
  src/views/Author/components/AuthorCard.js
Labels: bug

#93 Bugfix author search multiple search state
  src/views/Author/AuthorSearch.js
Labels: bug

#97 Hotfix: report not loading issue
  src/views/Author/AuthorReport.js
Labels: bug

#101 Remove publication condition
  src/views/Author/AuthorReport.js
Labels: bug

#102 Bugfix: Use site user name instead of scholar name
  src/views/Profile/components/ProfileHeader.js
Labels: bug

#103 Feature: add publication source to author report
  src/views/Author/AuthorReport.js
Labels: enhancement

#108 Hotfix: show all users in members options
  src/views/ManagingEntities/Team.js
Labels: bug

#133 Feature: switch to scimagojr journal service
  src/api/services.js
  src/views/Author/components/Publication.js
Labels: enhancement

#137 Bugfix: publications table overflow
  src/views/Author/components/Publication.js
  src/views/Author/components/Publications.js
Labels: bug
